meta_product_name: "Phobia"
meta_title: "Phobia - Scroll without fear"
meta_description: "Extension to block your Phobia"
meta_image: "meta_2_logo_transparent.png" # should exist in `app/assets/images/`
twitter_account: "@PhobiaLive"